# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport_webcast_im.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atransport_webcast_im.proto\"\x94\x06\n\ttransport\x1a\x86\x06\n\x07webcast\x1a\xfa\x05\n\x02im\x1a(\n\nPushHeader\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x1a\xda\x01\n\tPushFrame\x12\x10\n\x08_seq_i_d\x18\x01 \x01(\t\x12\x10\n\x08_log_i_d\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\x05\x12\x0e\n\x06method\x18\x04 \x01(\x05\x12\x31\n\x07headers\x18\x05 \x03(\x0b\x32 .transport.webcast.im.PushHeader\x12\x18\n\x10payload_encoding\x18\x06 \x01(\t\x12\x14\n\x0cpayload_type\x18\x07 \x01(\t\x12\x0f\n\x07payload\x18\x08 \x01(\x0c\x12\x14\n\x0c_lod_i_d_new\x18\t \x01(\t\x1a%\n\x0bPayloadInIm\x12\x16\n\x0e_compress_type\x18\x02 \x01(\x05\x1a\xa1\x02\n\x08Response\x12/\n\x08messages\x18\x01 \x03(\x0b\x32\x1d.transport.webcast.im.Message\x12\x0e\n\x06\x63ursor\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x65tch_interval\x18\x03 \x01(\t\x12\x0b\n\x03now\x18\x04 \x01(\t\x12\x14\n\x0cinternal_ext\x18\x05 \x01(\t\x12\x12\n\nfetch_type\x18\x06 \x01(\x05\x12\x1a\n\x12heartbeat_duration\x18\x08 \x01(\t\x12\x10\n\x08need_ack\x18\t \x01(\x08\x12\x13\n\x0bpush_server\x18\n \x01(\t\x12\x13\n\x0blive_cursor\x18\x0b \x01(\t\x12\x17\n\x0fhistory_no_more\x18\x0c \x01(\x08\x12\x14\n\x0cproxy_server\x18\r \x01(\t\x1a\xa1\x01\n\x07Message\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x0e\n\x06msg_id\x18\x03 \x01(\t\x12\x10\n\x08msg_type\x18\x04 \x01(\x05\x12\x0e\n\x06offset\x18\x05 \x01(\t\x12\x17\n\x0fneed_wrds_store\x18\x06 \x01(\x08\x12\x14\n\x0cwrds_version\x18\x07 \x01(\t\x12\x14\n\x0cwrds_sub_key\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport_webcast_im_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSPORT']._serialized_start=31
  _globals['_TRANSPORT']._serialized_end=819
  _globals['_TRANSPORT_WEBCAST']._serialized_start=45
  _globals['_TRANSPORT_WEBCAST']._serialized_end=819
  _globals['_TRANSPORT_WEBCAST_IM']._serialized_start=57
  _globals['_TRANSPORT_WEBCAST_IM']._serialized_end=819
  _globals['_TRANSPORT_WEBCAST_IM_PUSHHEADER']._serialized_start=63
  _globals['_TRANSPORT_WEBCAST_IM_PUSHHEADER']._serialized_end=103
  _globals['_TRANSPORT_WEBCAST_IM_PUSHFRAME']._serialized_start=106
  _globals['_TRANSPORT_WEBCAST_IM_PUSHFRAME']._serialized_end=324
  _globals['_TRANSPORT_WEBCAST_IM_PAYLOADINIM']._serialized_start=326
  _globals['_TRANSPORT_WEBCAST_IM_PAYLOADINIM']._serialized_end=363
  _globals['_TRANSPORT_WEBCAST_IM_RESPONSE']._serialized_start=366
  _globals['_TRANSPORT_WEBCAST_IM_RESPONSE']._serialized_end=655
  _globals['_TRANSPORT_WEBCAST_IM_MESSAGE']._serialized_start=658
  _globals['_TRANSPORT_WEBCAST_IM_MESSAGE']._serialized_end=819
# @@protoc_insertion_point(module_scope)
